# Generated by Django 3.1.2 on 2020-11-01 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_paper_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes_file',
            name='degree',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='college.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notes_file',
            name='year',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='college.year'),
            preserve_default=False,
        ),
    ]
