# Generated by Django 3.1.2 on 2020-11-01 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0007_auto_20201101_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_url',
            name='degree',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='college.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video_url',
            name='year',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='college.year'),
            preserve_default=False,
        ),
    ]
