# Generated by Django 3.1.2 on 2020-11-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0008_auto_20201101_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
